# Generated by Django 2.2.12 on 2022-04-19 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=0, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
