# Generated by Django 2.2.12 on 2022-06-18 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbox', '0003_auto_20220526_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
