# Generated by Django 2.2.12 on 2022-07-03 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbox', '0005_auto_20220703_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
