# Generated by Django 2.2.12 on 2022-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbox', '0007_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('team', models.ManyToManyField(related_name='team', to='checkbox.Team')),
            ],
        ),
    ]
