# Generated by Django 2.2.12 on 2022-07-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbox', '0008_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='task',
            field=models.ManyToManyField(related_name='task', to='checkbox.Task'),
        ),
    ]
